title:              Robert Dahlke Blog
email:              dahlkerobert1@gmail.com
description:        The Blog of Robert Dahlke
author:             Robert Dahlke
baseurl:            ""
url:                "https://RobertDahlke.github.io"

# Social Profiles
twitter_username:   RobertDahlke
github_username:    RobertDahlke
facebook_username:  RobertDahlke
instagram_username:  
linkedin_username:  robert-dahlke-253388211

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
